name: Build extension

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
  workflow_call:
    outputs:
      package-path:
        value: ${{ jobs.build.outputs.package-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      package-path: ${{ steps.build.outputs.package-path }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn global add @vscode/vsce

      - name: Build extension
        id: build
        run: |
          vsce package
          shopt -s nullglob
          files=(*.vsix)
          if [[ -z "${files[0]}" ]]; then
              exit 1
          fi
          echo "package-path=${files[0]}" >> "$GITHUB_OUTPUT"

      - name: Upload extension package
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: ${{ steps.build.outputs.package-path }}
          if-no-files-found: error
