name: Build extension

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
  workflow_call:
    outputs:
      package-path:
        value: ${{ jobs.build.outputs.package-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # TODO: detect generated path instead of hardcoding?
      PACKAGE_PATH: hex-casting.vsix
    outputs:
      package-path: ${{ env.PACKAGE_PATH }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn global add @vscode/vsce

      - name: Build extension
        run: vsce package --out ${{ env.PACKAGE_PATH }}

      - name: Upload extension package
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: ${{ env.PACKAGE_PATH }}
          if-no-files-found: error
