name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Tag
      wait:
        type: boolean
        default: false
        description: Wait for VS Marketplace validation

env:
  TAG: ${{ github.event_name == 'push' && github.ref_name || inputs.tag }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - if: github.event_name == 'push' || inputs.wait
        name: Wait for VS Marketplace validation
        run: sleep 5m
        shell: bash

      - name: Create GitHub release
        uses: elgohr/Github-Release-Action@v5
        with:
          title: ${{ env.TAG }}
          tag: ${{ env.TAG }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
